uploads = []
outputs = []

[[generated]]
id = "wHvM6x9XO04XTO1sxvAMm"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BUjkTTK4Gz3IKdshqsGFP"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"
